version: "3.6"
services:
  amachiromaker:
    build: .
    image: charlie0129/amachiromaker
    container_name: amachiromaker
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8090:80"
    environment:
      - "NODE_ENV=production"
